export const queryKeys = {
  readiness: ["backend-readiness"] as const,
  health: ["health"] as const,
  systemLoad: ["system-load"] as const,
  account: ["account"] as const,
  positions: ["positions"] as const,
  liveStatus: ["live-status"] as const,
  loopStatus: ["loop-status"] as const,
  strategyStatus: ["strategy-status"] as const,
  sessionStats: ["session-stats"] as const,
  riskSummary: ["risk-summary"] as const,
  riskPolicyVerdicts: ["risk-policy-verdicts"] as const,
  riskTradeTraces: ["risk-trade-traces"] as const,
  dbHealth: ["db-health"] as const,
  logs: (limit: number) => ["logs-tail", limit] as const,
};
