--
-- Phase 5B: backfill secondary indexes that S7.3 cold-start CREATE TABLE did not create.
-- Authoritative declaration sources: backend/core/db.py STATE_DB_DDL, backend/services/*, research/*,
-- migrations/state_pg/*. All statements are additive CREATE INDEX IF NOT EXISTS (idempotent).
-- Rationale: S7.3 rebuilt 75 runtime tables from code DDL but emitted 0 secondary indexes
-- running processes fail-closed on missing indexes after P4 schema-guard hardening.
-- This migration recreates every index whose table+columns exist in the rebuilt schema and
-- that is declared by production code (not test fixtures). It does NOT add tables or columns.
--

CREATE INDEX IF NOT EXISTS idx_auth_session_expiry ON auth_session(status, expires_at);
CREATE INDEX IF NOT EXISTS idx_auth_session_subject_status ON auth_session(subject, status, expires_at);
CREATE UNIQUE INDEX IF NOT EXISTS idx_auth_session_token_jti ON auth_session(token_jti);
CREATE INDEX IF NOT EXISTS idx_autonomous_learning_governance_eligible ON autonomous_learning_sample(sample_type, governance_eligibility_version, governance_eligible, governance_effective_weight, event_ts);
CREATE INDEX IF NOT EXISTS idx_autonomous_learning_sample_fingerprint ON autonomous_learning_sample(content_fingerprint, updated_at);
CREATE UNIQUE INDEX IF NOT EXISTS idx_autonomous_learning_sample_source ON autonomous_learning_sample(sample_type, source_table, source_id);
CREATE INDEX IF NOT EXISTS idx_autonomous_learning_sample_type ON autonomous_learning_sample(sample_type, label_status, event_ts);
CREATE INDEX IF NOT EXISTS idx_autonomy_health_snapshot_created ON autonomy_health_snapshot(created_at);
CREATE INDEX IF NOT EXISTS idx_autonomy_health_snapshot_posture ON autonomy_health_snapshot(posture, created_at);
CREATE INDEX IF NOT EXISTS idx_autonomy_scope_approval_created ON autonomy_scope_approval_event(created_at);
CREATE INDEX IF NOT EXISTS idx_autonomy_scope_approval_snapshot ON autonomy_scope_approval_event(snapshot_id, created_at);
CREATE INDEX IF NOT EXISTS idx_autonomy_scope_enforcement_created ON autonomy_scope_enforcement_event(created_at);
CREATE INDEX IF NOT EXISTS idx_autonomy_scope_enforcement_snapshot ON autonomy_scope_enforcement_event(snapshot_id, created_at);
CREATE INDEX IF NOT EXISTS idx_autonomy_scope_enforcement_status ON autonomy_scope_enforcement_event(status, created_at);
CREATE INDEX IF NOT EXISTS idx_brain_action_plan_created ON brain_action_plan(created_at);
CREATE INDEX IF NOT EXISTS idx_brain_action_plan_snapshot ON brain_action_plan(snapshot_id, created_at);
CREATE INDEX IF NOT EXISTS idx_brain_action_plan_type ON brain_action_plan(action_type, status);
CREATE INDEX IF NOT EXISTS idx_brain_action_plan_eval_created ON brain_action_plan_eval(created_at);
CREATE INDEX IF NOT EXISTS idx_brain_action_plan_eval_payload ON brain_action_plan_eval(payload_hash, created_at);
CREATE INDEX IF NOT EXISTS idx_brain_action_plan_eval_plan ON brain_action_plan_eval(plan_id, created_at);
CREATE INDEX IF NOT EXISTS idx_brain_action_plan_eval_run_plan ON brain_action_plan_eval(evaluation_run_id, plan_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_brain_action_plan_eval_run_plan_unique ON brain_action_plan_eval(evaluation_run_id, plan_id);
CREATE INDEX IF NOT EXISTS idx_brain_action_plan_eval_scope ON brain_action_plan_eval(scope_type, status, created_at);
CREATE INDEX IF NOT EXISTS idx_brain_action_plan_eval_payload_created ON brain_action_plan_eval_payload(created_at);
CREATE INDEX IF NOT EXISTS idx_brain_governance_candidate_created ON brain_governance_candidate(created_at);
CREATE INDEX IF NOT EXISTS idx_brain_governance_candidate_scope ON brain_governance_candidate(scope_type, scope_key, action);
CREATE INDEX IF NOT EXISTS idx_brain_governance_candidate_source ON brain_governance_candidate(source_agent, source_kind, created_at);
CREATE INDEX IF NOT EXISTS idx_brain_governance_candidate_stage ON brain_governance_candidate(proposal_stage, status, created_at);
CREATE INDEX IF NOT EXISTS idx_brain_candidate_review_candidate ON brain_governance_candidate_review(candidate_id, created_at);
CREATE INDEX IF NOT EXISTS idx_brain_candidate_review_status ON brain_governance_candidate_review(review_status, created_at);
CREATE INDEX IF NOT EXISTS idx_brain_live_ready_guardrail_created ON brain_live_ready_guardrail(created_at);
CREATE INDEX IF NOT EXISTS idx_brain_live_ready_guardrail_status ON brain_live_ready_guardrail(status, created_at);
CREATE INDEX IF NOT EXISTS idx_brain_low_impact_execution_created ON brain_low_impact_execution(created_at);
CREATE INDEX IF NOT EXISTS idx_brain_low_impact_execution_plan ON brain_low_impact_execution(plan_id, eval_id);
CREATE INDEX IF NOT EXISTS idx_brain_low_impact_execution_status ON brain_low_impact_execution(status, created_at);
CREATE INDEX IF NOT EXISTS idx_brain_medium_governance_candidate ON brain_medium_impact_governance(candidate_id);
CREATE INDEX IF NOT EXISTS idx_brain_medium_governance_created ON brain_medium_impact_governance(created_at);
CREATE INDEX IF NOT EXISTS idx_brain_medium_governance_plan ON brain_medium_impact_governance(plan_id, eval_id);
CREATE INDEX IF NOT EXISTS idx_brain_medium_governance_scope ON brain_medium_impact_governance(scope_type, status, created_at);
CREATE INDEX IF NOT EXISTS idx_brain_memory_score ON brain_memory(evidence_score, similarity_score);
CREATE INDEX IF NOT EXISTS idx_brain_memory_source ON brain_memory(source_table, source_id);
CREATE INDEX IF NOT EXISTS idx_brain_memory_type ON brain_memory(memory_type, created_at);
CREATE INDEX IF NOT EXISTS idx_brain_state_snapshot_created ON brain_state_snapshot(created_at);
CREATE INDEX IF NOT EXISTS idx_brain_state_snapshot_status ON brain_state_snapshot(status, created_at);
CREATE INDEX IF NOT EXISTS idx_ctrader_deals_pos ON ctrader_deals(position_id);
CREATE INDEX IF NOT EXISTS idx_ctrader_deals_ts ON ctrader_deals(exec_timestamp);
CREATE INDEX IF NOT EXISTS idx_decision_ledger_ts ON decision_ledger(decision_ts);
CREATE INDEX IF NOT EXISTS idx_evolution_decision_canonical ON evolution_decision(canonical_event_id, projection_type, created_at);
CREATE INDEX IF NOT EXISTS idx_evolution_decision_run ON evolution_decision(run_id, decision_type, created_at);
CREATE INDEX IF NOT EXISTS idx_evolution_events_type ON evolution_events(event_type);
CREATE INDEX IF NOT EXISTS idx_evolution_run_type ON evolution_run(run_type, status, started_at);
CREATE INDEX IF NOT EXISTS idx_experience_memory_regime ON experience_memory(regime_id, created_at);
CREATE INDEX IF NOT EXISTS idx_experience_memory_source ON experience_memory(source_table, source_id, created_at);
CREATE INDEX IF NOT EXISTS idx_experience_memory_source_append ON experience_memory(source_table, source_id, append_source);
CREATE INDEX IF NOT EXISTS idx_experience_memory_trade ON experience_memory(trade_id);
CREATE INDEX IF NOT EXISTS idx_experiments_status ON experiments(status);
CREATE INDEX IF NOT EXISTS idx_experiments_type ON experiments(experiment_type);
CREATE INDEX IF NOT EXISTS idx_factor_catalog_snapshot_created ON factor_catalog_snapshot(created_at);
CREATE INDEX IF NOT EXISTS idx_factor_governance_audit_created ON factor_governance_shadow_audit(created_at);
CREATE INDEX IF NOT EXISTS idx_factor_governance_audit_factor ON factor_governance_shadow_audit(factor, created_at);
CREATE INDEX IF NOT EXISTS idx_governance_mutation_projection ON governance_mutation_intent(projection_status, committed_at);
CREATE INDEX IF NOT EXISTS idx_governance_mutation_recovery ON governance_mutation_intent(status, projection_status, updated_at);
CREATE INDEX IF NOT EXISTS idx_governance_mutation_scope_status ON governance_mutation_intent(scope_type, scope_key, status, updated_at);
CREATE INDEX IF NOT EXISTS idx_governance_mutation_surface_status ON governance_mutation_intent(control_surface, status, updated_at);
CREATE INDEX IF NOT EXISTS idx_governance_mutation_v16 ON governance_mutation_intent(v16_command_id, created_at);
CREATE INDEX IF NOT EXISTS idx_incident_playbook_event_playbook ON incident_playbook_event(playbook_id, created_at);
CREATE INDEX IF NOT EXISTS idx_incident_playbook_event_type ON incident_playbook_event(event_type, created_at);
CREATE INDEX IF NOT EXISTS idx_incident_playbook_created ON incident_playbook_run(created_at);
CREATE INDEX IF NOT EXISTS idx_incident_playbook_scenario ON incident_playbook_run(scenario, created_at);
CREATE INDEX IF NOT EXISTS idx_jobs_claim_ready ON jobs(status, available_at, priority, created_at);
CREATE UNIQUE INDEX IF NOT EXISTS idx_jobs_kind_idempotency ON jobs(kind, idempotency_key);
CREATE INDEX IF NOT EXISTS idx_jobs_kind_status_created ON jobs(kind, status, created_at);
CREATE INDEX IF NOT EXISTS idx_jobs_running_lease ON jobs(status, lease_expires_at, kind);
CREATE INDEX IF NOT EXISTS idx_jobs_status ON jobs(status);
CREATE INDEX IF NOT EXISTS idx_learning_application_effect_scope ON learning_application_effect(scope, created_at);
CREATE INDEX IF NOT EXISTS idx_learning_application_scope ON learning_application_log(created_at);
CREATE INDEX IF NOT EXISTS idx_learning_experiment_reservation_scope ON learning_experiment_reservation(scope_type, scope_key, status);
CREATE INDEX IF NOT EXISTS idx_learning_experiment_reservation_status ON learning_experiment_reservation(status, expires_at);
CREATE INDEX IF NOT EXISTS idx_live_autonomy_unlock_created ON live_autonomy_unlock_event(created_at);
CREATE INDEX IF NOT EXISTS idx_live_autonomy_unlock_status ON live_autonomy_unlock_event(status, created_at);
CREATE INDEX IF NOT EXISTS idx_llm_advisory_audit_created ON llm_advisory_audit(created_at);
CREATE INDEX IF NOT EXISTS idx_llm_advisory_audit_target ON llm_advisory_audit(target_type, target_id, created_at);
CREATE INDEX IF NOT EXISTS idx_model_canary_review_candidate ON model_canary_review(candidate_id, created_at);
CREATE INDEX IF NOT EXISTS idx_model_canary_trial_candidate ON model_canary_trial(candidate_id, created_at);
CREATE INDEX IF NOT EXISTS idx_model_inference_candidate ON model_inference_audit(candidate_id, created_at);
CREATE INDEX IF NOT EXISTS idx_model_influence_decision_model_ts ON model_influence_decision(model_type, created_at);
CREATE INDEX IF NOT EXISTS idx_model_influence_decision_subject_ts ON model_influence_decision(subject_id, created_at);
CREATE INDEX IF NOT EXISTS idx_model_permission_audit_created ON model_permission_audit(created_at);
CREATE INDEX IF NOT EXISTS idx_model_permission_audit_model ON model_permission_audit(model_type, status, created_at);
CREATE INDEX IF NOT EXISTS idx_model_shadow_candidate_status ON model_shadow_candidate(status, updated_at);
CREATE INDEX IF NOT EXISTS idx_mutation_payload_created ON mutation_payload(created_at);
CREATE INDEX IF NOT EXISTS idx_nursery_exploration_budget ON nursery_exploration_reservation(trade_date, status, reason, setup_fingerprint);
CREATE INDEX IF NOT EXISTS idx_open_quality_shadow_audit_created ON open_quality_shadow_audit(created_at);
CREATE INDEX IF NOT EXISTS idx_open_quality_shadow_audit_position ON open_quality_shadow_audit(position_id, created_at);
CREATE INDEX IF NOT EXISTS idx_parameter_template_active_factor ON parameter_template_active(factor_id, regime_key, updated_at);
CREATE INDEX IF NOT EXISTS idx_parameter_template_registry_factor ON parameter_template_registry(factor_id, regime_key, template_version, active);
CREATE INDEX IF NOT EXISTS idx_parameter_template_release_candidate_factor ON parameter_template_release_candidate(factor_id, status, created_at);
CREATE INDEX IF NOT EXISTS idx_parameter_template_switch_log_factor ON parameter_template_switch_log(factor_id, regime_key, created_at);
CREATE INDEX IF NOT EXISTS idx_policy_suggestion_governance_eligible ON policy_suggestion(status, governance_eligibility_version, governance_eligible, created_at);
CREATE INDEX IF NOT EXISTS idx_policy_suggestion_scope ON policy_suggestion(scope_type, scope_key, status);
CREATE INDEX IF NOT EXISTS idx_position_quality_shadow_audit_created ON position_quality_shadow_audit(created_at);
CREATE INDEX IF NOT EXISTS idx_position_quality_shadow_audit_position ON position_quality_shadow_audit(position_id, created_at);
CREATE INDEX IF NOT EXISTS idx_position_supervisor_trace_action_outcome ON position_supervisor_trace(action, outcome, event_ts);
CREATE INDEX IF NOT EXISTS idx_position_supervisor_trace_position_ts ON position_supervisor_trace(position_id, event_ts);
CREATE INDEX IF NOT EXISTS idx_proposal_registry_source ON proposal_registry(source_agent, source_ref_type, updated_at);
CREATE INDEX IF NOT EXISTS idx_proposal_registry_source_ref_updated_v2 ON proposal_registry(source_ref_id, updated_at);
CREATE INDEX IF NOT EXISTS idx_proposal_registry_surface ON proposal_registry(control_surface, target_scope, status);
CREATE INDEX IF NOT EXISTS idx_proposal_registry_updated ON proposal_registry(updated_at);
CREATE INDEX IF NOT EXISTS idx_release_approval_decision ON release_approval_event(decision, created_at);
CREATE INDEX IF NOT EXISTS idx_release_approval_run ON release_approval_event(run_id, created_at);
CREATE INDEX IF NOT EXISTS idx_release_run_created ON release_run(created_at);
CREATE INDEX IF NOT EXISTS idx_release_run_status ON release_run(status, created_at);
CREATE INDEX IF NOT EXISTS idx_replay_report_created ON replay_report(created_at);
CREATE INDEX IF NOT EXISTS idx_replay_report_grade ON replay_report(evidence_grade, created_at);
CREATE INDEX IF NOT EXISTS idx_runtime_config_overlay_mutation ON runtime_config_overlay(mutation_id, updated_at);
CREATE INDEX IF NOT EXISTS idx_runtime_config_payload_created ON runtime_config_payload(created_at);
CREATE INDEX IF NOT EXISTS idx_runtime_config_snapshot_hash ON runtime_config_snapshot(config_hash, created_at);
CREATE INDEX IF NOT EXISTS idx_runtime_config_snapshot_payload ON runtime_config_snapshot(payload_hash, config_version);
CREATE INDEX IF NOT EXISTS idx_runtime_kv_updated ON runtime_kv(updated_at);
CREATE INDEX IF NOT EXISTS idx_shadow_factor_perf_updated ON shadow_factor_perf(updated_at);
CREATE INDEX IF NOT EXISTS idx_supervisor_counterfactual_history_source ON supervisor_counterfactual_history(counterfactual_id, created_at);
CREATE INDEX IF NOT EXISTS idx_supervisor_counterfactual_label ON supervisor_counterfactual_review(label, updated_at);
CREATE INDEX IF NOT EXISTS idx_supervisor_counterfactual_position ON supervisor_counterfactual_review(position_id, close_ts);
CREATE INDEX IF NOT EXISTS idx_v16_brain_command_authority ON v16_brain_command(target_agent, decision, authority_issued_at);
CREATE INDEX IF NOT EXISTS idx_v16_brain_command_claim ON v16_brain_command(target_agent, scope_type, claim_status, claim_expires_at);
CREATE INDEX IF NOT EXISTS idx_v16_brain_command_created ON v16_brain_command(created_at);
CREATE INDEX IF NOT EXISTS idx_v16_brain_command_scope ON v16_brain_command(scope_type, scope_key, created_at);
CREATE INDEX IF NOT EXISTS idx_v16_brain_command_target ON v16_brain_command(target_agent, status, created_at);
