#!/usr/bin/env python3
"""Migrate the complete SQLite state.db into PostgreSQL state_v1 schema."""

from __future__ import annotations

import argparse
import csv
import io
import json
import re
import sqlite3
import sys
import time
from pathlib import Path
from typing import Any

import psycopg

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))

from backend.core.db import STATE_DB, state_pg_dsn  # noqa: E402
from backend.core.state_store import STATE_SCHEMA  # noqa: E402


def quote_ident(name: str) -> str:
    return '"' + str(name).replace('"', '""') + '"'


def pg_type(sqlite_type: str, *, integer_pk: bool = False, table: str = "", column: str = "") -> str:
    raw = (sqlite_type or "").strip().upper()
    if integer_pk:
        return "BIGINT GENERATED BY DEFAULT AS IDENTITY"
    if table == "sqlite_sequence" and column == "seq":
        return "BIGINT"
    if "INT" in raw:
        return "BIGINT"
    if any(token in raw for token in ("REAL", "FLOA", "DOUB")):
        return "DOUBLE PRECISION"
    if "BLOB" in raw:
        return "BYTEA"
    return "TEXT"


def normalize_default(default: Any) -> str:
    if default is None:
        return ""
    text = str(default).strip()
    if not text:
        return ""
    upper = text.upper()
    if upper in {"NULL", "CURRENT_TIMESTAMP", "CURRENT_DATE", "CURRENT_TIME"}:
        return f" DEFAULT {text}"
    return f" DEFAULT {text}"


def sqlite_tables(conn: sqlite3.Connection) -> list[str]:
    rows = conn.execute(
        """
        SELECT name
        FROM sqlite_master
        WHERE type='table' AND (name NOT LIKE 'sqlite_%' OR name='sqlite_sequence')
        ORDER BY name
        """
    ).fetchall()
    return [str(row[0]) for row in rows]


def table_info(conn: sqlite3.Connection, table: str) -> list[sqlite3.Row]:
    return list(conn.execute(f"PRAGMA table_info({quote_ident(table)})").fetchall())


def table_indexes(conn: sqlite3.Connection, table: str) -> list[dict[str, Any]]:
    indexes: list[dict[str, Any]] = []
    for row in conn.execute(f"PRAGMA index_list({quote_ident(table)})").fetchall():
        name = str(row["name"])
        if name.startswith("sqlite_autoindex_"):
            continue
        cols = [str(info["name"]) for info in conn.execute(f"PRAGMA index_info({quote_ident(name)})").fetchall()]
        if not cols:
            continue
        indexes.append({"name": name, "unique": bool(row["unique"]), "columns": cols})
    return indexes


def create_table_sql(conn: sqlite3.Connection, table: str, schema: str) -> str:
    cols = table_info(conn, table)
    pk_cols = [row for row in cols if int(row["pk"] or 0) > 0]
    single_pk = len(pk_cols) == 1
    col_defs: list[str] = []
    table_constraints: list[str] = []
    for row in cols:
        name = str(row["name"])
        raw_type = str(row["type"] or "")
        is_single_integer_pk = single_pk and int(row["pk"] or 0) == 1 and "INT" in raw_type.upper()
        parts = [quote_ident(name), pg_type(raw_type, integer_pk=is_single_integer_pk, table=table, column=name)]
        if int(row["notnull"] or 0) and not is_single_integer_pk:
            parts.append("NOT NULL")
        if not is_single_integer_pk:
            parts.append(normalize_default(row["dflt_value"]))
        if single_pk and int(row["pk"] or 0) == 1:
            parts.append("PRIMARY KEY")
        col_defs.append(" ".join(part for part in parts if part))
    if len(pk_cols) > 1:
        ordered = sorted(pk_cols, key=lambda item: int(item["pk"]))
        table_constraints.append(
            "PRIMARY KEY (" + ", ".join(quote_ident(str(row["name"])) for row in ordered) + ")"
        )
    body = ",\n    ".join(col_defs + table_constraints)
    return f"CREATE TABLE {quote_ident(schema)}.{quote_ident(table)} (\n    {body}\n)"


def create_index_sql(index: dict[str, Any], table: str, schema: str) -> str:
    unique = "UNIQUE " if index["unique"] else ""
    cols = ", ".join(quote_ident(col) for col in index["columns"])
    return (
        f"CREATE {unique}INDEX IF NOT EXISTS {quote_ident(index['name'])} "
        f"ON {quote_ident(schema)}.{quote_ident(table)} ({cols})"
    )


def csv_value(value: Any) -> Any:
    if isinstance(value, bytes):
        return value.hex()
    return value


def copy_table(sqlite_conn: sqlite3.Connection, pg_conn, table: str, schema: str, batch_size: int) -> int:
    cols = table_info(sqlite_conn, table)
    names = [str(row["name"]) for row in cols]
    if not names:
        return 0
    count = 0
    quoted_cols = ", ".join(quote_ident(name) for name in names)
    copy_sql = f"COPY {quote_ident(schema)}.{quote_ident(table)} ({quoted_cols}) FROM STDIN WITH (FORMAT CSV, NULL '\\N')"
    cursor = sqlite_conn.execute(f"SELECT {quoted_cols} FROM {quote_ident(table)}")
    while True:
        rows = cursor.fetchmany(batch_size)
        if not rows:
            break
        buf = io.StringIO()
        writer = csv.writer(buf, lineterminator="\n")
        for row in rows:
            writer.writerow(["\\N" if value is None else csv_value(value) for value in row])
        buf.seek(0)
        with pg_conn.cursor().copy(copy_sql) as copy:
            copy.write(buf.read())
        count += len(rows)
    return count


def sync_identity_sequences(pg_conn, schema: str) -> None:
    rows = pg_conn.execute(
        """
        SELECT table_name, column_name
        FROM information_schema.columns
        WHERE table_schema = %s AND identity_generation IS NOT NULL
        ORDER BY table_name, column_name
        """,
        (schema,),
    ).fetchall()
    for table, column in rows:
        seq = pg_conn.execute(
            "SELECT pg_get_serial_sequence(%s, %s)",
            (f"{schema}.{table}", column),
        ).fetchone()[0]
        if not seq:
            continue
        max_id = int(pg_conn.execute(
            f"SELECT COALESCE(MAX({quote_ident(column)}), 0) FROM {quote_ident(schema)}.{quote_ident(table)}"
        ).fetchone()[0] or 0)
        if max_id <= 0:
            pg_conn.execute("SELECT setval(%s, 1, false)", (seq,))
        else:
            pg_conn.execute("SELECT setval(%s, %s, true)", (seq, max_id))


def snapshot_report(sqlite_conn: sqlite3.Connection, tables: list[str], schema: str, backup_dir: Path) -> None:
    report: dict[str, Any] = {"schema": schema, "created_at": time.time(), "tables": {}}
    for table in tables:
        cols = table_info(sqlite_conn, table)
        report["tables"][table] = {
            "count": sqlite_conn.execute(f"SELECT COUNT(*) FROM {quote_ident(table)}").fetchone()[0],
            "columns": [dict(row) for row in cols],
            "indexes": table_indexes(sqlite_conn, table),
        }
    backup_dir.mkdir(parents=True, exist_ok=True)
    (backup_dir / "sqlite_state_manifest.json").write_text(
        json.dumps(report, ensure_ascii=False, indent=2, default=str),
        encoding="utf-8",
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--sqlite-db", default=str(STATE_DB))
    parser.add_argument("--pg-dsn", default="")
    parser.add_argument("--schema", default=STATE_SCHEMA)
    parser.add_argument("--backup-dir", default="")
    parser.add_argument("--batch-size", type=int, default=5000)
    parser.add_argument("--drop-schema", action="store_true")
    args = parser.parse_args()

    sqlite_path = Path(args.sqlite_db)
    if not sqlite_path.exists():
        raise SystemExit(f"SQLite db not found: {sqlite_path}")
    dsn = args.pg_dsn or state_pg_dsn()
    if not dsn:
        raise SystemExit("PostgreSQL DSN missing; pass --pg-dsn or configure QUANT_STATE_PG_DSN")

    sqlite_conn = sqlite3.connect(f"file:{sqlite_path}?mode=ro", uri=True)
    sqlite_conn.row_factory = sqlite3.Row
    try:
        integrity = sqlite_conn.execute("PRAGMA integrity_check").fetchone()[0]
        if integrity != "ok":
            raise SystemExit(f"SQLite integrity_check failed: {integrity}")
        tables = sqlite_tables(sqlite_conn)
        if not tables:
            raise SystemExit("No SQLite tables found")
        if args.backup_dir:
            snapshot_report(sqlite_conn, tables, args.schema, Path(args.backup_dir))
        with psycopg.connect(dsn, autocommit=False) as pg_conn:
            if args.drop_schema:
                pg_conn.execute(f"DROP SCHEMA IF EXISTS {quote_ident(args.schema)} CASCADE")
            pg_conn.execute(f"CREATE SCHEMA IF NOT EXISTS {quote_ident(args.schema)}")
            for table in tables:
                pg_conn.execute(create_table_sql(sqlite_conn, table, args.schema))
            pg_conn.commit()
            for table in tables:
                pg_conn.execute(f"TRUNCATE TABLE {quote_ident(args.schema)}.{quote_ident(table)}")
                copied = copy_table(sqlite_conn, pg_conn, table, args.schema, args.batch_size)
                pg_conn.commit()
                print(f"{table}\t{copied}")
            for table in tables:
                for index in table_indexes(sqlite_conn, table):
                    pg_conn.execute(create_index_sql(index, table, args.schema))
            sync_identity_sequences(pg_conn, args.schema)
            pg_conn.commit()
    finally:
        sqlite_conn.close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
