import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

const root = process.cwd();
const read = (relative) => fs.readFileSync(path.join(root, relative), "utf8");
const app = read("src/App.tsx");
const shell = read("src/shell/WorkbenchShell.tsx");
const live = read("src/hooks/useLiveState.ts");
const client = read("src/api/client.ts");
const workbenchApi = read("src/api/workbench.ts");
const cache = read("src/cache/researchCache.ts");
const layout = read("src/shell/layout.ts");
const desktopBridge = read("src/desktop/bridge.ts");
const tauriCargo = read("src-tauri/Cargo.toml");
const desktopUpdater = read("src/desktop/updater.ts");
const tauriCapability = read("src-tauri/capabilities/default.json");
const tauriCommands = read("src-tauri/src/lib.rs") + read("src-tauri/src/commands.rs") + read("src-tauri/src/secure_store.rs");
const tauriReleaseConfig = read("src-tauri/tauri.release.conf.json");

for (const route of ["/login", "/trade-ops", "/risk-desk", "/research", "/governance", "/ops", "/workflow"]) assert.match(app, new RegExp(`path=\"${route.replaceAll("/", "\\/")}\"`));
for (const legacy of ["/overview", "/trading", "/pnl", "/risk", "/learning", "/models", "/v15", "/v16", "/performance", "/autonomy", "/ops/:section", "/governance/:section"]) {
  const escaped = legacy.replaceAll("/", "\\/").replaceAll(":", "\\:");
  assert.doesNotMatch(app, new RegExp(`path\\s*=\\s*[\\\"']${escaped}[\\\"']`), `legacy route remains: ${legacy}`);
}
assert.match(app, /RouteDeprecatedPage/);
assert.match(shell, /SafetyRail/);
assert.match(shell, /CommandPalette/);
assert.match(shell, /sidebar_collapsed/);
assert.doesNotMatch(shell, /ContextDock|context_dock|context-dock/);
assert.doesNotMatch(layout, /context_dock|split_ratios|panel_tree|active_tabs|collapsed_sections/);
assert.match(live, /Each WS message replaces the complete current snapshot/);
assert.match(live, /getWsTicket/);
assert.doesNotMatch(live, /setInterval|refetchInterval|polling|HTTP fallback|fallback to HTTP/);
assert.equal((live.match(/new WebSocket\(/g) ?? []).length, 1);
assert.doesNotMatch(client, /localStorage/);
assert.match(client, /navigator\.locks\.request/);
assert.match(client, /refreshInFlight/);
assert.doesNotMatch(workbenchApi, /Record<string, unknown>/);
assert.doesNotMatch(workbenchApi, /pick\(|recursive|fallback/);
assert.doesNotMatch(workbenchApi, /\/api\/dashboard/);
assert.match(cache, /market_snapshots/);
assert.match(cache, /replay_snapshots/);
assert.match(cache, /factor_snapshots/);
assert.match(cache, /research_snapshots/);
assert.match(cache, /cache_payload_not_allowlisted/);
assert.doesNotMatch(cache, /access_token.*put|refresh_token.*put/);
assert.match(layout, /quant\.ui\.layout\.v2/);
assert.match(layout, /decodeLayout/);
assert.match(desktopBridge, /set_refresh_material/);
assert.match(desktopBridge, /delete_refresh_material/);
assert.match(tauriCargo, /keyring\s*=\s*\{[^}]*windows-native/);
assert.match(desktopUpdater, /downloadAndInstall/);
assert.match(tauriReleaseConfig, /createUpdaterArtifacts/);
assert.match(tauriReleaseConfig, /"pubkey":\s*"dW50cnVzdGVk/);
assert.doesNotMatch(tauriReleaseConfig, /REPLACE_WITH_RELEASE_PUBLIC_KEY/);
assert.doesNotMatch(tauriCapability, /shell|sql|fs:default|http:default/);
assert.doesNotMatch(tauriCommands, /broker|RiskPolicy|PostgreSQL|postgres|market_buy|market_sell|runtime_config/);
console.log("workbench architecture test: ok");
