import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { aggregateFactViewState, factStateFromRaw, factViewState, readFact, readFactComponent } from "../api/fact.ts";

const now = Date.now() / 1000;
const envelope = (contract, state = "known", source = "server") => ({ envelope: "fact.v1", contract, state, source, observed_at: now, generated_at: now, stale_after_sec: 30, reason_code: state === "known" ? null : `reason_${state}`, components: {} });

assert.equal(factStateFromRaw("known"), "known");
assert.equal(factStateFromRaw("bad"), "unknown");
assert.equal(readFact(undefined, "risk.summary.v2").state, "unknown");
assert.equal(factViewState(readFact({ _fact: envelope("risk.summary.v2", "unknown") }, "risk.summary.v2")), "unknown");
assert.equal(aggregateFactViewState([{ fact: readFact({ _fact: envelope("a") }, "a") }, { fact: readFact({ _fact: envelope("b", "error") }, "b") }]), "error");
assert.equal(readFact({ _fact: envelope("a", "stale") }, "a").state, "stale");

const factSource = fs.readFileSync(path.join(process.cwd(), "src/api/workbench.ts"), "utf8");
const cacheSource = fs.readFileSync(path.join(process.cwd(), "src/cache/researchCache.ts"), "utf8");
assert.match(factSource, /decodeLiveSnapshot/);
assert.match(factSource, /decodeMarketBars/);
assert.match(factSource, /decodeRealizedPnlSeries/);
assert.match(factSource, /live\.realized-pnl\.v2/);
assert.match(factSource, /cumulativeFromServer/);
assert.match(factSource, /realized_pnl/);
assert.match(factSource, /decodeDecisionTrace/);
assert.match(factSource, /decodeHealth/);
assert.match(factSource, /decodeRecovery/);
assert.match(factSource, /decodeAlerts/);
assert.match(factSource, /risk\.summary\.v2/);
assert.match(factSource, /Promise\.allSettled/);
assert.match(factSource, /factor_id/);
assert.match(factSource, /request_failed/);
assert.match(factSource, /snapshot\.components/);
assert.match(factSource, /governance_candidates/);
assert.match(factSource, /readiness_dimensions/);
assert.match(factSource, /incident_control/);
assert.match(factSource, /allowed/);
assert.match(factSource, /review_id/);
assert.match(factSource, /replay_run_id/);
assert.match(factSource, /latest_review/);
assert.match(factSource, /live\.safety-freshness\.v1/);
assert.match(factSource, /reviewed_at/);
assert.match(fs.readFileSync(path.join(process.cwd(), "src/pages/GovernancePage.tsx"), "utf8"), /当前没有可审候选/);
assert.match(fs.readFileSync(path.join(process.cwd(), "src/pages/GovernancePage.tsx"), "utf8"), /最近一条持久化记录/);
assert.doesNotMatch(factSource, /root\.var|root\.kelly|root\.stress/);
assert.match(cacheSource, /FORBIDDEN_KEYS/);
assert.match(cacheSource, /cache_payload_not_allowlisted/);
console.log("workbench fact behavior: ok");
