import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "../..");
const read = (path) => readFileSync(resolve(root, path), "utf8");

const client = read("src/api/client.ts");
const auth = read("src/contexts/AuthContext.tsx");
const actionButton = read("src/components/ActionButton.tsx");
const liveHook = read("src/hooks/useLiveState.ts");
const trading = read("src/pages/TradingPage.tsx");
const overview = read("src/pages/OverviewPage.tsx");
const appShell = read("src/components/AppShell.tsx");
const models = read("src/pages/ModelsPage.tsx");
const miniLive = read("../miniprogram_v2/services/live.js");
const app = read("src/App.tsx");
const ops = read("src/pages/OpsPage.tsx");
const fact = read("src/api/fact.ts");
const v16 = read("src/pages/V16BrainPage.tsx");
const queryKeys = read("src/api/queryKeys.ts");

assert.match(client, /unauthorizedInFlight/);
assert.match(client, /refreshInFlight/);
assert.match(client, /runUnauthorizedOnce/);
assert.match(client, /navigator\.locks\.request\(AUTH_REFRESH_LOCK, refresh\)/);
assert.match(client, /currentToken && currentToken !== requestToken/);
assert.match(client, /refreshAccessToken\(requestToken\)/);
assert.match(auth, /window\.addEventListener\("storage", onStorage\)/);
assert.doesNotMatch(auth, /setUnauthorizedHandler\(\(\)\s*=>\s*\(\)\s*=>/);
assert.match(auth, /queryClient\.cancelQueries/);
assert.match(auth, /queryClient\.clear/);
assert.match(client, /postJson<StepUpResponse>\("\/api\/auth\/step-up", \{ password \}\)/);
assert.match(client, /publishAccessToken\(token\)/);
assert.match(client, /getApiErrorCode/);
assert.match(actionButton, /stepUpOnDemand/);
assert.match(actionButton, /autoComplete="current-password"/);
assert.match(actionButton, /role="alert"/);

assert.match(liveHook, /getWsTicket/);
assert.match(liveHook, /\?ticket=/);
assert.doesNotMatch(liveHook, /\?token=/);
assert.match(liveHook, /shouldApplyLiveSnapshot/);
assert.match(liveHook, /const next = normalized/);
assert.match(liveHook, /sole live authority/);
assert.match(liveHook, /hasSnapshotRef\.current/);
assert.match(liveHook, /snapshotRequestFailed/);
assert.match(liveHook, /clearLiveSnapshot/);
assert.match(liveHook, /const socketGenerationRef = useRef(?:<number>)?\(0\)/);
assert.match(liveHook, /const isCurrentSocket = \(\) =>/);
assert.match(liveHook, /wsRef\.current === socket/);
assert.match(liveHook, /generation !== socketGenerationRef\.current/);
assert.doesNotMatch(liveHook, /closeRequestedRef/);
assert.doesNotMatch(liveHook, /\}, \[enabled, pollIntervalMs, token, wsBase\]\);/);
assert.match(liveHook, /type SourceType = "websocket" \| "offline"/);
assert.doesNotMatch(liveHook, /getStateSnapshot/);
assert.doesNotMatch(liveHook, /LIVE_HTTP/);
assert.doesNotMatch(liveHook, /startFallbackSnapshotPolling/);
assert.doesNotMatch(liveHook, /http-fallback/);
assert.doesNotMatch(liveHook, /mergeLiveSnapshot/);
assert.doesNotMatch(liveHook, /LIVE_WS_SILENCE_TIMEOUT_MS/);
assert.doesNotMatch(liveHook, /armSocketSilenceTimeout/);
assert.doesNotMatch(liveHook, /lastMessageAtRef\.current/);
assert.doesNotMatch(liveHook, /WebSocket 暂无实时快照，等待重连/);
assert.match(liveHook, /LiveStateContext\.Provider/);
assert.match(app, /<LiveStateProvider enabled=\{authenticated\}>/);
assert.match(overview, /暂无实时快照/);
assert.doesNotMatch(overview, /WS 事实未知/);
assert.doesNotMatch(overview, /refetchInterval/);
assert.match(overview, /queryKey: queryKeys\.health[\s\S]*?retry: false/);
assert.match(overview, /queryKey: queryKeys\.health[\s\S]*?refetchOnWindowFocus: false/);
assert.match(overview, /pickNumber\(snapshotRecord, \["spot_quote\.mid", "current_price"/);
assert.match(overview, /label="XAU 最新报价"/);
assert.match(overview, /readFactComponent\(snapshot, "loop"/);
assert.match(overview, /readFactComponent\(snapshot, "account"/);
assert.doesNotMatch(trading, /refetchInterval/);
assert.doesNotMatch(trading, /HTTP 快照回退/);
assert.match(trading, /readFactComponent\(snapshot, "strategy"/);
assert.match(trading, /readFactComponent\(snapshot, "risk_inputs"/);
assert.match(trading, /riskData=\{risk\}/);
assert.doesNotMatch(appShell, /queryKey: queryKeys\.systemLoad[\s\S]*?refetchInterval/);
assert.match(appShell, /queryKey: queryKeys\.systemLoad[\s\S]*?staleTime: Infinity/);
assert.match(models, /queryKey: \["historical-backtest", backtestJobId\][\s\S]*?retry: false/);
assert.doesNotMatch(models, /queryKey: \["historical-backtest", backtestJobId\][\s\S]*?refetchInterval/);
assert.match(miniLive, /function scheduleReconnect\(\)/);
assert.match(miniLive, /ws_ticket_failed[\s\S]*?scheduleReconnect\(\)/);
assert.match(miniLive, /socketTask !== socket/);
assert.match(miniLive, /if \(pollInFlight\)\s*\{?\s*return pollInFlight/);
assert.match(miniLive, /if \(!force && wsFresh\)/);
assert.match(miniLive, /if \(now - lastPollAt < 1200\)/);
assert.match(queryKeys, /positions:\s*\["positions"\]/);
assert.match(queryKeys, /liveStatus:\s*\["live-status"\]/);
assert.match(trading, /status=\{connected && snapshot \? "WS 实时连接" : "暂无实时快照"\}/);

assert.match(fact, /missing_fact_envelope/);
assert.match(fact, /fact_contract_mismatch/);
assert.match(fact, /fact_source_unavailable/);
assert.match(fact, /export function factViewState/);
assert.match(fact, /export function aggregateFactViewState/);
assert.match(fact, /export function factViewLabel/);
assert.match(fact, /state:\s*"unknown"/);
assert.match(trading, /const startDisabled = !loopKnown \|\| loopRunning \|\| loopDraining \|\| stopRequested \|\| startBusy/);
assert.match(trading, /disabled=\{startDisabled\}/);
assert.match(trading, /const startConfirmMessage = startFactsKnown/);
assert.match(trading, /className="trading-actions"/);
assert.match(trading, /const stopResult = await stopTrading\(\)/);
assert.match(trading, /label="启动"[\s\S]*?stepUpOnDemand[\s\S]*?onAction=\{runStart\}/);
assert.match(trading, /label=\{loopStopping \? "停止中" : "停止"\}[\s\S]*?disabled=\{stopBusy \|\| stopRequested \|\| loopDraining\}/);
assert.match(trading, /label="紧急平仓"[\s\S]*?disabled=\{closeBusy\}/);
const emergencyAction = trading.match(/<ActionButton icon=\{RotateCcw\}[^\n]+/)?.[0] || "";
assert.doesNotMatch(emergencyAction, /stepUpOnDemand/);
assert.match(v16, /label="一次解锁"[\s\S]*?stepUpOnDemand[\s\S]*?onAction=\{runLiveUnlock\}/);
assert.match(ops, /!recoveryRegisteredVisible \? "未注册或未知"/);
assert.match(ops, /readFact\(recoveryQuery\.data, "ops\.auto-recovery\.v2"\)/);
assert.match(overview, /readFactComponent\(snapshot, "session", "live\.session-risk\.v2"\)/);
assert.match(ops, /!recoveryRegisteredVisible \? "未知" : loopHealthy/);
assert.match(ops, /!recoveryRegisteredVisible \? "未知" : schedulerHealthy/);
assert.match(ops, /loopHealthy && recoveryKnown \? "ok"/);
assert.match(ops, /schedulerHealthy && recoveryKnown \? "ok"/);
assert.match(ops, /"规则已配置 · 投递未知"/);

console.log("web fact/auth contract: ok");
