import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

const root = process.cwd();
const read = (relative) => fs.readFileSync(path.join(root, relative), "utf8");
const client = read("src/api/client.ts");
const auth = read("src/contexts/AuthContext.tsx");
const tokenStore = read("src/auth/tokenStore.ts");
const actionTicket = read("src/workspaces/WorkspaceBits.tsx");
const app = read("src/App.tsx");

assert.doesNotMatch(client, /localStorage|sessionStorage|IndexedDB/);
assert.doesNotMatch(auth, /localStorage|sessionStorage/);
assert.match(tokenStore, /let accessToken: string \| null = null/);
assert.match(tokenStore, /Access tokens are intentionally never serialized/);
assert.match(client, /refreshInFlight/);
assert.match(client, /navigator\.locks\.request\(AUTH_REFRESH_LOCK, refresh\)/);
assert.match(client, /current && current !== requestToken/);
assert.match(client, /runUnauthorizedOnce/);
assert.match(client, /await persistRefreshMaterial\(result\.refresh_token\)/);
assert.match(client, /credentials: "include"/);
assert.match(client, /\/api\/auth\/ws-ticket/);
assert.match(client, /isTauri\(\) \? DEFAULT_DESKTOP_API_BASE_URL/);
assert.match(client, /https:\/\/www\.zhuzhu666\.icu/);
assert.match(client, /stepUpAuth/);
assert.match(actionTicket, /stepUpAuth/);
assert.match(actionTicket, /autoComplete="current-password"/);
assert.match(actionTicket, /mutationId/);
assert.match(actionTicket, /auditId/);
assert.match(actionTicket, /commitStatus/);
assert.match(app, /RouteDeprecatedPage/);
console.log("workbench auth contract: ok");
