import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

const root = process.cwd();
const read = (relative) => fs.readFileSync(path.join(root, relative), "utf8");
const source = ["src/pages/TradeOpsPage.tsx", "src/pages/RiskDeskPage.tsx", "src/pages/ResearchPage.tsx", "src/pages/GovernancePage.tsx", "src/pages/OpsPage.tsx"].map(read).join("\n");
const locale = read("src/i18n/zh-CN.ts");
assert.match(locale, /交易运营/);
assert.match(locale, /风险台/);
assert.match(locale, /研究实验室/);
assert.match(locale, /治理中心/);
assert.match(locale, /运维中心/);
assert.match(source, /交易运营/);
assert.match(source, /风险台/);
assert.match(source, /研究实验室/);
assert.match(source, /治理中心/);
assert.match(source, /运维中心/);
assert.match(source, /FactBadge/);
assert.match(source, /SourceLine/);
assert.match(source, /服务端|server/i);
assert.doesNotMatch(source, /calculateVaR|calculateCVaR|kelly\s*=|var95\s*=|cvar95\s*=/);
assert.match(read("src/pages/TradeOpsPage.tsx"), /submitEmergencyClose/);
assert.match(read("src/pages/TradeOpsPage.tsx"), /getRealizedPnlSeries/);
assert.match(read("src/pages/TradeOpsPage.tsx"), /PnlChart/);
assert.doesNotMatch(read("src/pages/TradeOpsPage.tsx"), /getMarketBars|MarketChart/);
assert.match(read("src/pages/OpsPage.tsx"), /submitIncidentTighten/);
assert.match(read("src/pages/ResearchPage.tsx"), /putResearchCache/);
assert.match(read("src/pages/ResearchPage.tsx"), /决策追踪 \/ PIT/);
assert.match(read("src/pages/ResearchPage.tsx"), /getReplayDecisionTrace/);
assert.match(read("src/pages/ResearchPage.tsx"), /MarketChart/);
assert.doesNotMatch(read("src/pages/ResearchPage.tsx"), /research-bar-strip/);
assert.match(read("src/design-system/MarketChart.tsx"), /candle-wick/);
assert.match(read("src/design-system/MarketChart.tsx"), /candle-body/);
assert.match(read("src/design-system/PnlChart.tsx"), /pnl-line/);
assert.match(read("src/design-system/PnlChart.tsx"), /DEFAULT_INITIAL_CAPITAL = 500/);
assert.match(read("src/pages/GovernancePage.tsx"), /Coordinator/);
assert.match(read("src/shell/commands.ts"), /risk-reduction/);
assert.match(read("src/shell/commands.ts"), /serverGate/);
console.log("workbench product contract: ok");
