import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

const root = process.cwd();
const read = (relative) => fs.readFileSync(path.join(root, relative), "utf8");
const source = ["src/pages/TradeOpsPage.tsx", "src/pages/RiskDeskPage.tsx", "src/pages/ResearchPage.tsx", "src/pages/GovernancePage.tsx", "src/pages/OpsPage.tsx"].map(read).join("\n");
const shell = read("src/shell/WorkbenchShell.tsx");
const serverStatus = read("src/shell/ServerStatusCard.tsx");
const workbenchApi = read("src/api/workbench.ts");
const styles = read("src/styles/workbench.css");
const locale = read("src/i18n/zh-CN.ts");
const tradeOps = read("src/pages/TradeOpsPage.tsx");
const loginPage = read("src/pages/LoginPage.tsx");
assert.match(locale, /交易运营/);
assert.match(locale, /风险台/);
assert.match(locale, /研究实验室/);
assert.match(locale, /治理中心/);
assert.match(locale, /运维中心/);
assert.match(source, /交易运营/);
assert.match(source, /风险台/);
assert.match(source, /研究实验室/);
assert.match(source, /治理中心/);
assert.match(source, /运维中心/);
assert.match(source, /FactBadge/);
assert.match(source, /SourceLine/);
assert.match(source, /服务端|server/i);
assert.match(loginPage, /auth-shell/);
assert.match(loginPage, /auth-submit/);
assert.match(loginPage, /SECURE ACCESS/);
assert.match(styles, /\.auth-root/);
assert.match(styles, /\.auth-card/);
assert.doesNotMatch(source, /calculateVaR|calculateCVaR|kelly\s*=|var95\s*=|cvar95\s*=/);
assert.match(read("src/pages/TradeOpsPage.tsx"), /submitEmergencyClose/);
assert.match(read("src/pages/TradeOpsPage.tsx"), /getRealizedPnlSeries/);
assert.match(read("src/pages/TradeOpsPage.tsx"), /PnlChart/);
assert.match(tradeOps, /最近一天/);
assert.match(tradeOps, /最近一周/);
assert.match(tradeOps, /realizedPnlScope/);
assert.match(tradeOps, /queryKey: \["workbench", "realized-pnl", realizedPnlScope\]/);
assert.match(tradeOps, /账户快照/);
assert.match(tradeOps, /account-metric-grid/);
assert.match(tradeOps, /hasAccountValue/);
assert.match(tradeOps, /hasFreeMarginValue/);
assert.match(tradeOps, /现货中间价/);
assert.doesNotMatch(tradeOps, /cockpit-live-overview|最后完整快照|新增风险门/);
assert.doesNotMatch(tradeOps, /getRiskSnapshot|风险上下文|risk-context-panel/);
assert.match(styles, /\.pnl-panel \{ grid-column: 1 \/ -1; grid-row: 2; \}/);
assert.doesNotMatch(styles, /risk-context-panel|risk-context-banner|cockpit-risk-panel/);
assert.doesNotMatch(styles, /cockpit-orbit|cockpit-hero-layout|status-list|cockpit-live-overview/);
assert.match(styles, /account-metric-grid/);
assert.doesNotMatch(read("src/pages/TradeOpsPage.tsx"), /getMarketBars|MarketChart/);
const opsPage = read("src/pages/OpsPage.tsx");
const workflowPage = read("src/pages/WorkflowPage.tsx");
assert.match(opsPage, /getLogTail/);
assert.match(opsPage, /ops-log-panel/);
assert.match(opsPage, /ops-signal-panel/);
assert.match(opsPage, /ops-runtime-panel/);
assert.doesNotMatch(opsPage, /submitIncidentTighten|ServerActionTicket|事故控制/);
assert.doesNotMatch(read("src/pages/OpsPage.tsx"), /getReadinessView|ops-readiness-panel|后端就绪度/);
assert.match(styles, /\.ops-grid \{ grid-template-rows: 440px 300px; \}/);
assert.match(styles, /\.ops-log-panel \{ grid-column: 1 \/ span 8; grid-row: 1 \/ span 2; min-height: 0; \}/);
assert.match(styles, /\.ops-signal-panel, \.ops-runtime-panel \{ grid-column: 9 \/ span 4; \}/);
assert.match(styles, /\.ops-issue-list \{[^}]*overflow-y: auto;/);
assert.doesNotMatch(styles, /ops-health-panel|ops-incident-panel|ops-recovery-panel|incident-banner|incident-actions/);
assert.match(workflowPage, /useLiveState/);
assert.match(workflowPage, /getReadinessView/);
assert.match(workflowPage, /observed_at/);
assert.match(workflowPage, /不表示产生订单/);
assert.match(workflowPage, /getLearningLoopData/);
assert.match(workflowPage, /一体化神经网络/);
assert.match(workflowPage, /智能学习是从 state_v1 分出的反馈回路/);
assert.match(workflowPage, /当前学习卡点/);
assert.match(workflowPage, /实时主干/);
assert.match(workflowPage, /回流出口/);
assert.doesNotMatch(workflowPage, /<LearningOverview/);
assert.doesNotMatch(workflowPage, /<WorkflowLane/);
assert.match(workflowPage, /原因码/);
assert.match(workflowPage, /buildArchitectureMap/);
assert.match(workflowPage, /项目架构拓扑/);
assert.match(workflowPage, /架构节点详情/);
assert.match(workflowPage, /DialogSurface/);
assert.match(workflowPage, /DialogClose/);
assert.match(workflowPage, /API \/ WSS 事实投影/);
assert.match(workflowPage, /Committed runtime projection/);
assert.match(workbenchApi, /learning\.summary\.v2/);
assert.match(workbenchApi, /dataset\/readiness/);
assert.match(workbenchApi, /model\/shadow-queue/);
assert.match(workbenchApi, /effect-quality/);
assert.match(styles, /\.architecture-panel/);
assert.match(styles, /\.architecture-integrated-summary/);
assert.match(styles, /\.workflow-page \{ text-rendering: optimizeLegibility; \}/);
assert.match(styles, /\.architecture-node strong \{[^}]*font: 600 13px\/1\.4 var\(--font-display\)/);
assert.match(styles, /\.architecture-node-role \{[^}]*font: 10px\/1\.5 var\(--font-ui\)/);
assert.match(styles, /\.architecture-node time \{[^}]*font: 9px\/1\.4 var\(--mono\)/);
assert.match(styles, /\.architecture-lane-flow/);
assert.match(styles, /architecture-travel/);
assert.match(styles, /\.architecture-detail-dialog/);
assert.doesNotMatch(styles, /learning-overview-panel|learning-loop-panel|learning-detail-grid-layout|workflow-flow-panel|workflow-lane-live/);
assert.match(read("src/pages/ResearchPage.tsx"), /putResearchCache/);
assert.match(read("src/pages/ResearchPage.tsx"), /决策追踪 \/ PIT/);
assert.match(read("src/pages/ResearchPage.tsx"), /getReplayDecisionTrace/);
assert.match(read("src/pages/ResearchPage.tsx"), /MarketChart/);
assert.match(read("src/pages/ResearchPage.tsx"), /历史仓位/);
assert.match(read("src/pages/ResearchPage.tsx"), /selected-bar-window/);
assert.match(read("src/pages/ResearchPage.tsx"), /前置/);
assert.match(read("src/pages/ResearchPage.tsx"), /出场/);
assert.match(read("src/pages/ResearchPage.tsx"), /selectedExitTs/);
assert.match(read("src/pages/ResearchPage.tsx"), /ChartSystemView/);
assert.match(read("src/pages/ResearchPage.tsx"), /系统观点/);
assert.match(styles, /\.decision-trace-panel \{ grid-column: 1 \/ -1; grid-row: 3; \}/);
assert.match(styles, /\.research-row-main/);
assert.match(styles, /\.research-row-meta/);
assert.match(styles, /text-overflow: ellipsis/);
assert.match(read("src/design-system/MarketChart.tsx"), /chart-focus-line/);
assert.match(read("src/design-system/MarketChart.tsx"), /chart-position-holding/);
assert.match(read("src/design-system/MarketChart.tsx"), /tone: "entry" \| "exit"/);
assert.doesNotMatch(read("src/pages/ResearchPage.tsx"), /research-bar-strip/);
assert.match(read("src/design-system/MarketChart.tsx"), /candle-wick/);
assert.match(read("src/design-system/MarketChart.tsx"), /candle-body/);
assert.match(read("src/design-system/PnlChart.tsx"), /pnl-line/);
assert.match(read("src/design-system/PnlChart.tsx"), /preserveAspectRatio=\"none\"/);
assert.match(read("src/design-system/PnlChart.tsx"), /DEFAULT_INITIAL_CAPITAL = 500/);
assert.match(read("src/design-system/PnlChart.tsx"), /baselineValue/);
assert.match(read("src/design-system/PnlChart.tsx"), /baselineLabel/);
assert.match(tradeOps, /fullPnlScope = realizedPnlScope === "all"/);
assert.match(tradeOps, /pnlChartBaseline = fullPnlScope \? DEFAULT_INITIAL_CAPITAL : 0/);
assert.match(tradeOps, /不含原始资金/);
assert.match(read("src/pages/GovernancePage.tsx"), /Coordinator/);
assert.match(read("src/shell/commands.ts"), /risk-reduction/);
assert.match(read("src/shell/commands.ts"), /serverGate/);
assert.match(shell, /ServerStatusCard/);
assert.match(serverStatus, /getSystemLoad/);
assert.match(serverStatus, /CPU/);
assert.match(serverStatus, /内存/);
assert.match(serverStatus, /磁盘/);
console.log("workbench product contract: ok");
